---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: 您可以設定電子郵件以接收 Upgrade Health Checker 報告。 
---
= 透過電子郵件接收升級健全狀況檢查程式報告
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker 可以將報告直接傳送至您的收件匣。您可以透過 config.yaml 檔案或命令列參數啟用此功能。啟用後，Upgrade Health Checker 會將產生的報告（HTML、Excel 或 JSON 格式）透過 SMTP 伺服器傳送給一個或多個收件者。停用此功能後，將不會傳送任何報告。如果報告產生失敗且已啟用電子郵件功能，Upgrade Health Checker 會將日誌檔案透過電子郵件傳送給已設定的收件者。



[[configure-using-the-config-yaml-file]]
== 使用 config.yaml 檔案進行設定

您可以透過在 config.yaml 檔案中啟用電子郵件報告、新增 SMTP 伺服器詳細資訊以及指定收件者位址和報告格式來設定電子郵件設定。

. 在 config.yaml 檔案中啟用電子郵件報告。
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. 新增 SMTP 組態設定、寄件者詳細資料和主旨：
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. 新增收件者電子郵件地址，並設定系統透過電子郵件傳送的報告格式，例如 HTML、EXCEL、JSON 或全部。您也可以使用驗證和加密：
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
    USE_SMTP_AUTH: true
    USE_TLS: true
    USE_SSL: true
    USERNAME: "user@example.com"
    PASSWORD: "********"
----




[[configure-using-command-line-arguments]]
== 使用命令列引數進行組態設定

您可以使用命令列引數設定基本電子郵件設定，以啟用報告、指定收件者及選擇報告格式。

. 使用命令列引數啟用電子郵件報告：
+
[listing]
----
./uhc --email-enabled=true
----
. 提供收件者電子郵件地址：
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. 設定透過電子郵件傳送的報告格式，例如 HTML、EXCEL、JSON：
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
您可以使用命令列參數或 config.yaml 檔案設定以下三個屬性。其餘所有屬性只能在 config.yaml 檔案中設定：

* 已啟用電子郵件
* 電子郵件收件者
* 電子郵件報告格式


請注意，命令列參數會置換 config.yaml 檔案的值。

例如：

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====